server:
  port: ${SERVER_PORT:4001}

security:
  jwt:
    key-store: classpath:JWTKeystore.p12
    key-store-password: devdcorespass
    key-pair-alias: jwt-key
    key-pair-password: devdcorespass
    public-key: classpath:jwt-signing-public-key.txt

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-account-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  devtools:
    remote:
      secret: KALSDJFLNVMSDJFGIERJGLESALRGJLAJFGLASDFJLASDFM
    livereload:
      enabled: true

  jpa:
    open-in-view: true
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    dbcp2:
      validation-query: SELECT 1;
    tomcat:
      validation-interval: 80000
    initialization-mode: always
#    data: classpath*:data.sql

  flyway:
    table: account_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 0.9
    enabled: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.wolverine.solutions.*: DEBUG

management:
  endpoint:
    hystrix:
      stream:
        enabled: true